<<<<<<< HEAD
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] ?? "postgresql://neondb_owner:npg_PUCTF4dIuWA0@ep-long-bar-a1qrgbvn-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require",
=======
import { defineConfig } from "prisma/config";
import * as fs from "fs";
import * as path from "path";

// Load .env manually for Prisma CLI context
const envPath = path.resolve(__dirname, ".env");
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, "utf-8").split("\n");
  for (const line of lines) {
    const match = line.match(/^([^#=]+)=(.*)$/);
    if (match) {
      const key = match[1].trim();
      const value = match[2].trim().replace(/^["']|["']$/g, "");
      process.env[key] ??= value;
    }
  }
}

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL!,
>>>>>>> 607b0b216c834b27ddb27ee7dbf87bdd6a4e98c8
  },
});
